//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TiroAlBlancoConsolaApp {
    using System;
    
    
    /// <summary>
    ///   Clase de recurso fuertemente tipado, para buscar cadenas traducidas, etc.
    /// </summary>
    // StronglyTypedResourceBuilder generó automáticamente esta clase
    // a través de una herramienta como ResGen o Visual Studio.
    // Para agregar o quitar un miembro, edite el archivo .ResX y, a continuación, vuelva a ejecutar ResGen
    // con la opción /str o recompile su proyecto de VS.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class TiroAlBlanco {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal TiroAlBlanco() {
        }
        
        /// <summary>
        ///   Devuelve la instancia de ResourceManager almacenada en caché utilizada por esta clase.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("TiroAlBlancoConsolaApp.TiroAlBlanco", typeof(TiroAlBlanco).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Reemplaza la propiedad CurrentUICulture del subproceso actual para todas las
        ///   búsquedas de recursos mediante esta clase de recurso fuertemente tipado.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a intentos .
        /// </summary>
        internal static string Attempts {
            get {
                return ResourceManager.GetString("Attempts", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Por favor, introduzca angulo (grados): .
        /// </summary>
        internal static string degrees {
            get {
                return ResourceManager.GetString("degrees", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a blanco destruido .
        /// </summary>
        internal static string destroyed {
            get {
                return ResourceManager.GetString("destroyed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Misil cae a.
        /// </summary>
        internal static string fall {
            get {
                return ResourceManager.GetString("fall", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Por favor, Introduce tu nombre: .
        /// </summary>
        internal static string inputName {
            get {
                return ResourceManager.GetString("inputName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Misil cae a menos de 1 m.
        /// </summary>
        internal static string missileLess {
            get {
                return ResourceManager.GetString("missileLess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Error, velocidad fuera de rango.
        /// </summary>
        internal static string mistake1 {
            get {
                return ResourceManager.GetString("mistake1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Error, angulo fuera de rango.
        /// </summary>
        internal static string mistake2 {
            get {
                return ResourceManager.GetString("mistake2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Lanzamiento del jugador .
        /// </summary>
        internal static string PlayerLaunch {
            get {
                return ResourceManager.GetString("PlayerLaunch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Distancia al objetivo: .
        /// </summary>
        internal static string TargetDistance {
            get {
                return ResourceManager.GetString("TargetDistance", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a ¿Qué tipo de objetivo quieres (1-fijo, 2-movil)?: .
        /// </summary>
        internal static string tiypeObjetive {
            get {
                return ResourceManager.GetString("tiypeObjetive", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Por favor, introduzca velocidad (Km/h): .
        /// </summary>
        internal static string velocity {
            get {
                return ResourceManager.GetString("velocity", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Bienvenido .
        /// </summary>
        internal static string welcome {
            get {
                return ResourceManager.GetString("welcome", resourceCulture);
            }
        }
    }
}
